language: csharp
solution: build/CoiniumServ.sln
os:
  - osx
  - linux
mono:
  - latest
  - 4.6.2
  - 4.4.2
  - 4.2.4
  - 4.0.5
  - 3.12
dotnet: 
  - 1.0.0-preview2-003121  
  - 1.0.0-preview2-003131
script:
- xbuild build/CoiniumServ.sln /p:Configuration="Debug"
- xbuild build/CoiniumServ.sln /p:Configuration="Release"
- mono contrib/xunit/xunit.console.clr4.x86.exe src/Tests/bin/Debug/CoiniumServ.Tests.dll
- mono contrib/xunit/xunit.console.clr4.x86.exe src/Tests/bin/Release/CoiniumServ.Tests.dll
